IMAGE_INSTALL += " \
	task-lxde-extended \
	\
	xinput-calibrator \
	\
	lxde-common \
	openbox \
	openbox-theme-clearlooks \
	openbox-theme-onyx \
	lxde-icon-theme \
	hicolor-icon-theme \
	lxdm \
	lxsession \
	lxmenu-data \
	menu-cache \
	lxappearance \
	obconf \
	lxrandr \
	lxpanel \
	\
	lxtask \
	lxpolkit \
	lxsession-edit \
	\
	lxshortcut \
	lxlauncher \
	pcmanfm \
	leafpad \
	gpicview \
	lxterminal \
	lxinput \
"
#	angstrom-task-lxde \
#	task-lxde-xserver \
#	task-lxde-xserver-base \
#	lxappearance-obconf \
#	xkbd \
#	xcursor-themes \
#	policykit-gnome \
